### PR TITLE
Added 4 released tools (IgDiscover, WhatsHap, ChIP-seq QC workflow and SweFreq)

### PR DESCRIPTION
**Pull request by pareng**
Three of these are from WABI (IgDiscover, WhatsHap, ChIP-seq QC workflow).

I also added SweFreq (using minimal yml), because the tools page is live now and I think SweFreq should be listed ASAP. We should ask one of the SweFreq developers to add it to bio.tools, and after that we can replace SeqFreq.yml with a file generated based on bio.tools.

### CODE REVIEW

**Comment by nmb** [comment]
Is the ChIP-seq QC pipeline included twice? There's both ChIP-seq_QC.yml and ClusterFlow_ChIP-seq_QC.yml.

**Comment by pareng** [comment]
Ojdå, filen ChIP-seq_QC.yml hade jag tänkt radera. Jag hade visst bara raderat den lokalt, men inte från repot. Ska jag göra en ny pull req efter att jag tagit bort den, eller kan du acceptera valda delar?

**Comment by glormph** [comment]
If you add a commit to the branch it will be included in the pull req, so you don't have to open a new one.

**Review by glormph — APPROVED** [review]
Looks fine to me from here. @nmb do we have some sort of test site just to see there is nothing that messes up the UI?

**Pull request merged**
